# Generated by Django 4.0.1 on 2022-03-13 02:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'School Staff'), (3, 'Driver'), (4, 'General')], default=4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'permissions': (('view', 'can view user'), ('change', 'can edit user'), ('delete', 'can delete user'), ('add', 'can create user')),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('is_complete', models.BooleanField(default=False)),
                ('color_id', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('view', 'can view route'), ('change', 'can edit route'), ('delete', 'can delete route'), ('add', 'can create route')),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival', models.TimeField(default=datetime.time(0, 0))),
                ('departure', models.TimeField(default=datetime.time(0, 0))),
                ('location_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='ht_buses_app.location')),
            ],
            options={
                'permissions': (('view', 'can view school'), ('change', 'can edit school'), ('delete', 'can delete school'), ('add', 'can create school')),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_school_id', models.IntegerField(default=0)),
                ('in_range', models.BooleanField(default=False)),
                ('route_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='ht_buses_app.route')),
                ('school_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.school')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view', 'can view student'), ('change', 'can edit student'), ('delete', 'can delete student'), ('add', 'can create student')),
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_by', models.IntegerField(default=None)),
                ('arrival', models.TimeField(default=datetime.time(0, 0))),
                ('departure', models.TimeField(default=datetime.time(0, 0))),
                ('location_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.location')),
                ('route_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.route')),
            ],
            options={
                'permissions': (('view', 'can view stop'), ('change', 'can edit stop'), ('delete', 'can delete stop'), ('add', 'can create stop')),
            },
        ),
        migrations.AddField(
            model_name='route',
            name='school_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.location'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['route_id'], name='ht_buses_ap_route_i_40b211_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_id'], name='ht_buses_ap_school__45bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user_id'], name='ht_buses_ap_user_id_68f1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['route_id'], name='ht_buses_ap_route_i_a0796b_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['school_id'], name='ht_buses_ap_school__3a38f1_idx'),
        ),
    ]
