# Generated by Django 4.0.1 on 2022-03-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0003_remove_user_is_parent_alter_user_role_log_bus'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['route_id'], name='ht_buses_ap_route_i_3529ee_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user_id'], name='ht_buses_ap_user_id_3d299f_idx'),
        ),
    ]
