# Generated by Django 4.0.1 on 2022-03-29 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0004_log_ht_buses_ap_route_i_3529ee_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), related_name='account_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
