# Generated by Django 4.0.1 on 2022-04-01 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0005_student_account_alter_student_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
