# Generated by Django 4.0.1 on 2022-01-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route_id',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=models.SET(0), to='ht_buses_app.route'),
        ),
    ]
