# Generated by Django 4.0.1 on 2022-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0009_alter_student_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
