# Generated by Django 4.0.1 on 2022-02-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0010_school_lat_school_long_user_lat_user_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
