# Generated by Django 4.0.1 on 2022-02-01 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0011_alter_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(0), to='ht_buses_app.route'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
