# Generated by Django 4.0.1 on 2022-02-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0012_alter_student_route_id_alter_student_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='route_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='ht_buses_app.route'),
        ),
    ]
