# Generated by Django 4.0.1 on 2022-02-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0014_location_remove_school_address_remove_school_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.location'),
        ),
    ]
