# Generated by Django 4.0.1 on 2022-02-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0015_alter_school_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='ht_buses_app.location'),
        ),
    ]
