# Generated by Django 4.0.1 on 2022-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0016_alter_school_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stop_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='ht_buses_app.stop'),
        ),
    ]
