# Generated by Django 4.0.1 on 2022-02-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0016_alter_school_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure',
        ),
    ]
