# Generated by Django 4.0.1 on 2022-02-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0017_remove_route_arrival_remove_route_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='color_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='in_range',
            field=models.BooleanField(default=False),
        ),
    ]
