# Generated by Django 4.0.1 on 2022-02-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0018_route_color_id_student_in_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='lng',
        ),
    ]
