# Generated by Django 4.0.1 on 2022-02-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0019_rename_long_location_lng'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
            ],
        ),
    ]
