# Generated by Django 4.0.1 on 2022-02-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0020_alter_location_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
    ]
