# Generated by Django 4.0.1 on 2022-02-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0021_alter_route_managers_alter_school_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
