# Generated by Django 4.0.1 on 2022-02-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0022_alter_student_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stop',
            managers=[
            ],
        ),
    ]
