# Generated by Django 4.0.1 on 2022-03-03 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ht_buses_app', '0023_alter_stop_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'permissions': (('view', 'can view route'), ('change', 'can edit route'), ('delete', 'can delete route'), ('add', 'can create route'))},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('view', 'can view school'), ('change', 'can edit school'), ('delete', 'can delete school'), ('add', 'can create school'))},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'permissions': (('view', 'can view stop'), ('change', 'can edit stop'), ('delete', 'can delete stop'), ('add', 'can create stop'))},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view', 'can view student'), ('change', 'can edit student'), ('delete', 'can delete student'), ('add', 'can create student'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view', 'can view user'), ('change', 'can edit user'), ('delete', 'can delete user'), ('add', 'can create user'))},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Driver'), (3, 'General'), (4, 'School Staff')], default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
