# Generated by Django 4.0.1 on 2022-02-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0023_alter_stop_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(default=None),
        ),
    ]
