# Generated by Django 4.0.1 on 2022-03-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0025_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Driver'), (3, 'General'), (4, 'School Staff')]),
        ),
    ]
