# Generated by Django 4.0.1 on 2022-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0024_alter_route_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (3, 'Driver'), (4, 'General'), (2, 'School Staff')], default=4),
        ),
    ]
