# Generated by Django 4.0.1 on 2022-02-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0026_remove_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
    ]
