# Generated by Django 4.0.1 on 2022-03-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0025_alter_user_phone_number'),
        ('ht_buses_app', '0026_alter_user_role'),
    ]

    operations = [
    ]
