# Generated by Django 4.0.1 on 2022-03-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0028_remove_user_role_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('patch_school', 'can edit school'), ('create_school', 'can create school'))},
        ),
    ]
