# Generated by Django 4.0.1 on 2022-03-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0030_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
