# Generated by Django 4.0.1 on 2022-03-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0031_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': ()},
        ),
    ]
