# Generated by Django 4.0.1 on 2022-03-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0032_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'permissions': (('view', 'can view school'), ('change', 'can edit school'), ('delete', 'can delete school'), ('add', 'can create school'))},
        ),
    ]
