# Generated by Django 4.0.1 on 2022-03-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0033_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'permissions': (('view', 'can view route'), ('change', 'can edit route'), ('delete', 'can delete route'), ('add', 'can create route'))},
        ),
        migrations.AlterModelOptions(
            name='stop',
            options={'permissions': (('view', 'can view stop'), ('change', 'can edit stop'), ('delete', 'can delete stop'), ('add', 'can create stop'))},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('view', 'can view student'), ('change', 'can edit student'), ('delete', 'can delete student'), ('add', 'can create student'))},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view', 'can view user'), ('change', 'can edit user'), ('delete', 'can delete user'), ('add', 'can create user'))},
        ),
    ]
