# Generated by Django 4.0.1 on 2022-01-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_school_id', models.IntegerField(default=0)),
                ('route_id', models.ForeignKey(default=0, on_delete=models.SET(0), to='ht_buses_app.route')),
                ('school_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.school')),
                ('user_extended_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.userextended')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='school_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ht_buses_app.school'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['route_id'], name='ht_buses_ap_route_i_40b211_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school_id'], name='ht_buses_ap_school__45bb69_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user_extended_id'], name='ht_buses_ap_user_ex_2f4625_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['school_id'], name='ht_buses_ap_school__3a38f1_idx'),
        ),
    ]
