# Generated by Django 4.0.1 on 2022-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
