# Generated by Django 4.0.1 on 2022-01-19 08:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0002_alter_route_managers_alter_school_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('routeTables', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
                ('schoolsTable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('studentsTable', django.db.models.manager.Manager()),
            ],
        ),
    ]
