# Generated by Django 4.0.1 on 2022-01-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht_buses_app', '0003_alter_route_managers_alter_school_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
